/**
 * github.mjs — GitHub CLI (gh) interactions.
 *
 * Functions receive `config` as first parameter and use `config.ghRepo`, `config.repoPath`.
 */

import { execFileSync } from "child_process";
import { log } from "./log.mjs";

// ─── Create Pull Request ─────────────────────────────────────────────────────

export function createPR(config, title, body, { baseBranch = "main" } = {}) {
  const args = ["pr", "create", "--repo", config.ghRepo, "--title", title, "--body-file", "-", "--base", baseBranch];
  try {
    const prUrl = execFileSync(
      "gh",
      args,
      { cwd: config.repoPath, encoding: "utf-8", input: body, timeout: 30000 }
    ).trim();

    log(`PR created: ${prUrl} (base: ${baseBranch})`, config);
    return prUrl;
  } catch (e) {
    // PR already exists for this branch — find and reuse it
    const match = e.stderr?.match(/already exists:\s*(https:\/\/\S+)/);
    if (match) {
      const existingUrl = match[1];
      log(`PR already exists, reusing: ${existingUrl}`, config);
      return existingUrl;
    }
    throw e;
  }
}

// ─── Merge Pull Request (squash) ─────────────────────────────────────────────

export function mergePR(config, prUrl) {
  execFileSync(
    "gh",
    ["pr", "merge", "--repo", config.ghRepo, "--squash", "--delete-branch", prUrl],
    { cwd: config.repoPath, encoding: "utf-8", timeout: 30000 }
  );
  log("PR merged", config);
}

// ─── List merged PRs matching a pattern ──────────────────────────────────────

export function listMergedPRs(config, pattern) {
  const prJson = execFileSync(
    "gh",
    ["pr", "list", "--repo", config.ghRepo, "--state", "merged", "--limit", "200", "--json", "number,title,mergeCommit"],
    { cwd: config.repoPath, encoding: "utf-8", timeout: 30000 }
  );
  return JSON.parse(prJson).filter((pr) => pr.title.match(pattern));
}

// ─── Create Sprint PR (sprint → main) ──────────────────────────────────────

export function createSprintPR(config, sprintBranch) {
  const title = `Sprint merge: ${sprintBranch}`;
  const body = `Merge sprint branch \`${sprintBranch}\` into main.\n\nGenerated by autodev --close-sprint`;
  return createPR(config, title, body, { baseBranch: "main" });
}
